name: CI
on: push
jobs:
    prod-check:
        if: ${{ github.ref == 'refs/heads/main'}}
        runs-on: ubuntu-latest
        env:
            MY_ENV_VAR: ${{ null }}
        steps:
            - run: echo "Deploying to production server on branch $MY_ENV_VAR $GITHUB_REF"