name: CI
on: push
jobs:
    prod-check:
        if: ${{ github.ref == 'refs/heads/main'}}
        runs-on: ubuntu-latest
        env:
            MY_ENV_VAR: ${{ 21 }}
            MY_ENV_VAR_TWO: ${{ 2}}
            MY_EXPRESSION: ${{ 21 > 1 }}
        steps:
            - run: echo "Deploying to production server on $MY_EXPRESSION branch $MY_ENV_VAR $GITHUB_REF"