name: lesson-six-secret
on: push
jobs:
    use-secret-workflow:
      runs-on: ubuntu-latest
      steps:
        - name: Check out a private tools repo
          uses: actions/checkout@v7
          with:
            repository: octo-org/private-tools
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
            path: private-tools
            persist-credentials: false
        - name: Query the github API
          env:
            GH_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          run: gh api user